import { I18n } from "i18n-js";
const translations = {
  en: {
    welcome: "Welcome to",
    dudda: "Dudda!",
    loading: "Loading...",
    home: "Home",
    profile: "Profile",
    schedule: "Schedule",
    deposit: "Payments",
    supporte: "Contact Us",
    shareSocial: "Share",
    signup: "Sign Up",
    login: "Log In",
    password: "Password",
    forgetPassword: "Forgot your password?",
    forrgetPassMess:
      "Please enter your email address and we will send you a link where you can reset your password.",
    logout: "Log Out",
    sendingCode: "Sending code...",
    sendCode: "Send code",
    emailRequired: "Email required",
    enterEmail: "Please enter your email.",
    emailSent: "Email sent",
    checkmailToresetPass: "Please check your email to reset your password.",
    errorSendingMail: "Error sending code",
    errorSendingMailMess:
      "There was an error sending the password reset code. Please verify the information you entered and try again.",
    confirmLogout: "Are you sure you want to log out?",
    cancel: "Cancel",
    back: "Back",
    signupMessage: "Sign up and start teaching with us!",
    notification: "Notifications",
    currentBalence: "Current balance",
    noNotification: "No notifications yet.",
    classSchedule: "Scheduled lessons",
    noClass: "No lessons scheduled yet.",
    notVerified:
      "Verify your account and start teaching. Submit your admissions exam.",
    takeExam: "Take exam",
    firstName: "First name",
    lastName: "Last name",
    dob: "Birthday",
    phone: "Phone number",
    repeatPassword: "Confirm password",
    incompleteInform: "Incomplete information",
    noEmailRPass: "Please enter your email and password.",
    incompleteInformMess:
      "Please, complete your information to be able to register.",
    validateAgeMess: "Minimum age: You must be 18 years or older to register",
    confirmPass: "Try again : Passwords do not match.",
    errorSignup: "Error registering",
    errorSignupMess:
      "An error occurred during registration. Please verify your details and try again.",
    email: "Email",
    personelInform: "PERSONAL INFORMATION",
    ok: "OK",
    privacy: "PRIVACY",
    location: "Location",
    deleteAcount: "Delete account",
    deleteAcountDesc:
      "Your information will be permanently deleted, it is not possible to reverse this action.",
    confirm: "Keep",
    sunday: "S",
    monday: "M",
    tuesday: "T",
    wednesday: "W",
    thursday: "T",
    friday: "F",
    saturday: "S",
    chooseYourSchedule: "Choose your schedule",
    chooseYourScheduleDetail:
      "Green hours indicate free time. We will only book lessons at those times. Choose wisely as cancellations may reduce future bookings. Our system favors tutors with fewer cancellations.",
    bankAccountNumberTab: "Bank account code",
    bankAccountNumber: "Account Num.",
    interbankAccountNumberTab: "Interbank account code (IAC)",
    interbankAccountNumber: "AIC",
    paymentHistory: "Payments history",
    noPayment: "No payments yet.",
    name: "Name *",
    paternalLastName: "Last name *",
    sex: "Sex *",
    male: "Male",
    female: "Female",
    termsAndConds: "Terms and Conditions",
    acceptTermsAndConds: "I have read and accept the terms and conditions.",
    continue: "Continue",
    reportUser: "Report user, Do you want to report this user?",
    report: "Report",
    cancelClass: "Cancel lesson",
    cancelClassConfirm: "Are you sure you want to cancel this lesson?",
    settings: "Settings",
    settingsDesc: "Please select one of the following options.",
    report_User: "Report user",
    cancelClass: "Cancel lesson",
    cancelClass_desc:
      "First cancellation free. Subsequent cancellations may lead to permanent suspension.",
    ruleOut: "Rule out",
    thankyou_for_report: "Thank you for your report!",
    thankyou_for_report_desc:
      "We'll review it below and get back to you shortly.",
    emailNotOpened: "The email could not be opened. Please try again later.",
    videoCall: "Video call",
    videoCallJoin:
      "You are about to join the video call. Do you want to continue?",
    reasonOFCancel: "Explain to us the reason for the cancellation.",
    writeHere: "Write here...",
    confirmation: "Confirmation",
    conFirm: "Confirm",
    confirmSaveSchedule: "Are you sure you want to save the schedules?",
    updatedSchedule: "Schedules have been successfully updated.",
    permissionDenied: "Permission denied",
    errorNotificationToken: "Error getting notification token!",
    loactionPermision: "Location permission denied",
    loactionPermisionDesc:
      "Please enable location for this app in your phone's settings",
    gotoSettings: "Go to Settings",
    disableLocation: "Disable location",
    disableLocationDesc: "Are you sure you want to turn location off?",
    deactivate: "Deactivate",
    turnOffNotification: "Turn off notifications",
    turnOffNotificationDesc: "Are you sure you want to turn off notifications?",
    deleteNotification: "Delete notification",
    deleteNotificationDesc:
      "Are you sure you want to remove this notification?",
    eleminate: "Eliminate",
    with: "With",
    of: "of",
    to: "to",
    needHelp: "Need help?",
    needHelpDesc:
      "Please send us a message or call us and our team will contact you.",
    writeTous: "Text us",
    callUs: "Call us",
    faildToLogin: "Failed to login",
    faildToLoginDesc:
      "Sorry, we couldn't find an account with that information. Please check your details and try again.",
    emailOrPasswordisWrong:
      "The email or password is incorrect. Please verify your credentials and try again.",
    errorMinimumAge: "Minimum age required",
    errorMinimumAgeDesc: "You must be at least 18 years old to register.",
    understood: "Understood",
    sex: "Sex",
    scheduleAClass: "schedule a class",
    scheduleClass: "schedule class",
    duration: "Duration",
    hour: "hour",
    min: "minutes",
    selectADate: "Select a date",
    start: "Start",
    end: "End",
    minimumTime: "The minimum time for a class is 1 hour.",
    maximumTime: "The maximum time for a class is 3 hours.",
    and: "and",
    noTutor: "No tutors found",
    noTutorDesc: "Please try a different time or contact support.",
    classHistory: "Class history",
    noClassHistory: "You haven't had any class yet.",
    scheduledClass: "Scheduled classes",
    noscheduledClass: "You don't have any classes scheduled yet.",
    completeLessonRegistration:
      "To complete the registration, please send us our phone number WhatsApp the deposit voucher or Yape.",
    businessName: "Business Name:",
    interBank: "Interbank (CCI)",
    installWhatsapp: "Install Whatsapp",
    installWhatsappDesc:
      "Make sure you have WhatsApp installed on your device.",
    sendusAmess: "Send us a message",
    sendusAmessDesc:
      "For now, schedule your class through WhatsApp, write to us and we'll help you.",
    resetPassword: "Reset password",
    resetPasswordMess: "Enter the verification code and your new password.",
    verificationCode: "Verification code",
    newPassword: "New Password",
    incompleteInform:
      "Please, complete your information to be able to register.",
    tryAgain: "Try again",
    passwordNotMatch: "Passwords do not match.",
    emailSent: "Email sent",
    reportUserDesc: "Do you want to report this user?",
    joinMeet: "Join the meeting?",
    joinMeetDesc: "Are you sure you want to join the meeting?",
    join: "Join",
    soonMoreCourses: "Soon more courses!",
    soonMoreCoursesDesc:"Currently, we only offer math classes.",
    math:"Mathematics",
  },
  es: {
    math:"Matemáticas",
    soonMoreCoursesDesc: "Actualmente, solo ofrecemos clases de matemáticas.",
    soonMoreCourses: "¡Pronto más cursos!",
    join: "Unirse",
    joinMeetDesc: "¿Estás seguro que deseas unirte a la reunión?",
    joinMeet: "¿Unirte a la reunión?",
    reportUserDesc: "¿Deseas reportar a este usuario?",
    passwordNotMatch: "Las contraseñas no coinciden.",
    emailSent: "Correo enviado",
    tryAgain: "Intente de nuevo",
    incompleteInform: "Por favor, completa tus datos para poder registrarte.",
    resetPassword: "Reestablecer contraseña",
    resetPasswordMess:
      "Ingrese el código de verificación y su nueva contraseña.",
    newPassword: "Nueva contraseña",
    verificationCode: "Código de verificación",
    welcome: "Bienvenido a",
    dudda: "¡Dudda!",
    loading: "Cargando...",
    home: "Inicio",
    profile: "Perfil",
    schedule: "Horario",
    deposit: "Depósitos",
    supporte: "Contáctanos",
    shareSocial: "Compartir",
    signup: "Registrarse",
    login: "Iniciar sesión",
    password: "Contraseña",
    forgetPassword: "¿Olvidaste tu contraseña?",
    forrgetPassMess:
      "Por favor, ingresa tu dirección de correo electrónico y te enviaremos un enlace donde podrás restablecer tu contraseña.",
    logout: "Cerrar sesión",
    sendingCode: "Enviando código...",
    sendCode: "Enviar código",
    emailRequired: "Correo electrónico requerido",
    enterEmail: "Por favor, ingresa tu correo electrónico.",
    emailSent: "Correo electrónico enviado",
    checkmailToresetPass:
      "Por favor, revisa tu correo electrónico para restablecer tu contraseña.",
    errorSendingMail: "Error al enviar el código",
    errorSendingMailMess:
      "Ocurrió un error al enviar el código de restablecimiento de contraseña. Por favor, verifica la información que ingresaste e inténtalo de nuevo.",
    confirmLogout: "¿Estás seguro de que deseas cerrar sesión?",
    cancel: "Cancelar",
    back: "Atrás",
    signupMessage: "¡Regístrate y empieza a enseñar con nosotros!",
    notification: "Notificaciones",
    currentBalence: "Saldo actual",
    noNotification: "Aún no tienes ninguna notificación.",
    classSchedule: "Clases programadas",
    noClass: "Aún no tienes clases programadas.",
    notVerified:
      "Verifica tu cuenta para empezar a recibir clases. Realiza tu examen de admisión.",
    takeExam: "Dar exam",
    firstName: "Nombre",
    lastName: "Apellidos",
    sex: "Sexo *",
    male: "Hombre",
    female: "Mujer",
    dob: "Fecha de nacimiento",
    phone: "Teléfono celular",
    repeatPassword: "Repetir contraseña",
    incompleteInform: "Información incompleta",
    noEmailRPass: "Por favor, ingresa tu correo electrónico y contraseña.",
    incompleteInformMess:
      "Por favor, completa tu información para poder registrarte.",
    validateAgeMess: "Edad mínima: debes tener 18 años o más para registrarte",
    confirmPass: "Intenta de nuevo: las contraseñas no coinciden.",
    errorSignup: "Error al registrarse",
    errorSignupMess:
      "Ocurrió un error durante el registro. Por favor, verifica tus datos e inténtalo de nuevo.",
    email: "Correo electrónico",
    personelInform: "INFORMACIÓN PERSONAL",
    ok: "Aceptar",
    privacy: "PRIVACIDAD",
    location: "Ubicación",
    deleteAcount: "Eliminar cuenta",
    deleteAcountDesc:
      "Tu información se eliminará permanentemente, no es posible revertir esta acción.",
    confirm: "Aceptar",
    sunday: "D",
    monday: "L",
    tuesday: "M",
    wednesday: "X",
    thursday: "J",
    friday: "V",
    saturday: "S",
    chooseYourSchedule: "Elige tu horario",
    chooseYourScheduleDetail:
      "Las horas verdes indican tiempo libre y solo programaremos clases en esos horarios. Elige sabiamente, ya que las cancelaciones pueden reducir las futuras reservas. Nuestro sistema favorece a los tutores con menos cancelaciones.",
    bankAccountNumberTab: "Número de cuenta bancaria",
    bankAccountNumber: "Nº de cuenta",
    interbankAccountNumberTab: "Número de cuenta interbancaria (CCI)",
    interbankAccountNumber: "CCI",
    paymentHistory: "Historial de pagos",
    noPayment: "Aún no tienes ningún pago.",
    name: "Nombre *",
    paternalLastName: "Apellido *",
    termsAndConds: "Términos y condiciones",
    acceptTermsAndConds: "He leído y acepto los términos y condiciones.",
    continue: "Continuar",
    reportUser: "Reportar usuario, ¿Deseas reportar a este usuario?",
    report: "Reportar",
    cancelClass: "Cancelar clase",
    cancelClassConfirm: "¿Estás seguro de que quieres cancelar esta clase?",
    settings: "Configuración",
    settingsDesc: "Por favor, selecciona una de las siguientes opciones.",
    report_User: "Reportar usuario",
    cancelClass: "Cancelar clase",
    cancelClass_desc:
      "La primera cancelación es gratuita. Las cancelaciones posteriores pueden llevar a la suspensión permanente.",
    ruleOut: "Descartar",
    thankyou_for_report: "¡Gracias por tu reporte!",
    thankyou_for_report_desc:
      "Lo revisaremos a continuación y te responderemos en breve.",
    emailNotOpened:
      "No se pudo abrir el correo electrónico. Por favor, inténtalo de nuevo más tarde.",
    videoCall: "Llamada de video",
    videoCallJoin:
      "Estás a punto de unirte a la llamada de video. ¿Deseas continuar?",
    reasonOFCancel: "Explícanos el motivo de la cancelación.",
    writeHere: "Escribe aquí...",
    confirmation: "Confirmación",
    conFirm: "Confirmar",
    confirmSaveSchedule: "¿Estás seguro de que quieres guardar los horarios?",
    updatedSchedule: "Los horarios se han actualizado correctamente.",
    permissionDenied: "Permiso denegado",
    errorNotificationToken: "¡Error al obtener el token de notificación!",
    loactionPermision: "Permiso de ubicación denegado",
    loactionPermisionDesc:
      "Por favor, habilita la ubicación para esta aplicación en la configuración de tu teléfono",
    gotoSettings: "Ir a Configuración",
    disableLocation: "Desactivar ubicación",
    disableLocationDesc:
      "¿Estás seguro de que quieres desactivar la ubicación?",
    deactivate: "Desactivar",
    turnOffNotification: "Desactivar notificaciones",
    turnOffNotificationDesc:
      "¿Estás seguro de que quieres desactivar las notificaciones?",
    deleteNotification: "Eliminar notificación",
    deleteNotificationDesc:
      "¿Estás seguro de que quieres eliminar esta notificación?",
    eleminate: "Eliminar",
    with: "Con",
    of: "de",
    to: "a",
    needHelp: "¿Necesitas ayuda?",
    needHelpDesc:
      "Por favor, envíanos un mensaje o llámanos y nuestro equipo se pondrá en contacto contigo.",
    writeTous: "Escríbenos",
    callUs: "Llámanos",
    faildToLogin: "Error al iniciar sesión",
    faildToLoginDesc:
      "Lo sentimos, no pudimos encontrar una cuenta con esa información. Por favor, verifica tus datos e inténtalo de nuevo.",
    emailOrPasswordisWrong:
      "El correo electrónico o la contraseña son incorrectos. Por favor, verifica tus credenciales e inténtalo de nuevo.",
    errorMinimumAge: "Edad mínima requerida",
    errorMinimumAgeDesc: "Debes tener al menos 18 años para registrarte.",
    understood: "Entendido",
    duration: "Duración",
    hour: "hora",
    min: "minutos",
    selectADate: "Selecciona una fecha",
    start: "Inicio",
    scheduleAClass: "Agenda una clase",
    scheduleClass: "Agendar clase",
    end: "Fin",
    minimumTime: "El tiempo mínimo para una clase es de 1 hora.",
    maximumTime: "El tiempo máximo para una clase es de 3 horas.",
    and: "y",
    noTutor: "No se encontraron tutores",
    noTutorDesc:
      "Por favor, intente un horario diferente o contacte al soporte.",
    classHistory: "Historial de clases",
    noClass: " Aún no has tenido ninguna clase.",
    scheduledClasses: "Clases programadas",
    noscheduledClass: " Aún no tienes ninguna clase programada.",
    completeLessonRegistration:
      "Para concluir con el registro, por favor, envíanos a nuestro número de WhatsApp el voucher del depósito o Yape.",
    businessName: "Razón Social",
    interBank: "Interbancaria (CCI)",
    installWhatsapp: "Instala WhatsApp",
    installWhatsappDesc:
      "Asegúrate de tener WhatsApp instalado en tu dispositivo.",
    sendusAmess: "Envíanos un mensaje",
    sendusAmessDesc:
      "Por ahora, programa tu clase a través de WhatsApp, escríbenos y te ayudamos.",
  },
};
export const i18n = new I18n(translations);
